CREATE TABLE IF NOT EXISTS patient (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  lastname VARCHAR(200) NOT NULL,
  firstname VARCHAR(200) NOT NULL,
  birth DATE NOT NULL,
  gender VARCHAR(1) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL
);