version: '3'

services:
  mysqldb:
    image: mysql/mysql-server:latest
    networks:
      - patientNetwork-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=patientLocale
      - MYSQL_USER=root
      - MYSQL_PASSWORD= root
    ports:
      - "3308:3306"

  ms_patient:
    image: ms_patient:latest
    ports:
      - "8081:8081"
    networks:
      - patientNetwork-mysql
    depends_on:
      - mysqldb

networks:
  patientNetwork-mysql:
    driver: bridge


